name: instag
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-cuda=11.7
  - plyfile=0.8.1
  - python=3.9
  - pip=22.3.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - ffmpeg
  - openh264
  - mkl=2023.0
  - pip:
    - ./submodules/diff-gaussian-rasterization
    - ./submodules/simple-knn
    - ./gridencoder
    - numpy==1.24.3
    - pillow==9.5.0
    - scipy
    - tensorboard
    - opencv-python
    - tensorboardX

    - pandas
    - tqdm
    - matplotlib
    - rich
    - packagingpip install lpips imageio-ffmpeg librosa transformers==4.30.2

    - scikit-learn

    - face_alignment
    - python_speech_features
    - numba
    - resampy
    - pyaudio
    - soundfile
    - configargparse

    - lpips
    - imageio-ffmpeg
    - librosa
    - transformers==4.30.2
